### ISSUE TITLE
Create User Input Address modal.

### ISSUE THREAD

**Issue by emswann** [emswann/still-open#12]
Add  User Input Address modal to webpage.

Implement as a form.

Include the following information:

(shown in order)
Street Address
City
State
Zipcode (type = number)

Header will include X for close.

Footer will include Submit button.

**Comment by robertbernardbrown** [comment]
@emswann Testing

**Comment by emswann** [comment]
Need to hold off on implementing this issue until #11 is merged with Master. That issue changed some of the <head> section to add Bootstrap jquery includes.

It will be easier if we wait and then just build on that change.
