### ISSUE TITLE
Determine user's current location using GPS.

### ISSUE THREAD

**Issue by emswann** [emswann/still-open#28]
API? or JavaScript library?

**Comment by cslewislives** [comment]
The Icons can be used by You for any number of personal or commercial projects including software application, mobile application, documentation, presentation, computer game, gui design, web design, web application, advertisement, illustration, video for You or for Your clients, without having to pay additional licensing fees.
The Icons can be used by any number of developers and designers of Your company.

You must put backlink with credits to http://www.icons-land.com
	1. In case of website You must put a backlink with credits on every page where The Icons are used. Link must be placed in easy-to-see and recognizable place.
	2. In case of software application You must put a backlink with credits on About form of the application.
	3. In other cases You must put a backlink with credits on some page or screen of Your product or on relative website.
