### ISSUE TITLE
Add hours, picture, and price to restaurant info modal.

### ISSUE THREAD

**Issue by robertbernardbrown** [emswann/still-open#38]
Couldn't get hours from Yelp for modal, but can get if is-open.

Need to get hours from Google Maps.

Use is-open to determine along with hours if should populate on list.

Finalize what is being populated on restaurant info modal.

Do we still want a picture? Price?

**Comment by emswann** [comment]
is-open shows whether or not the restaurant is still in business. Will need to check this value along with the hours to decide whether or not to populate on the list.

If the business is closed, then it should not appear on the list.

**Comment by emswann** [comment]
@robertbernardbrown suggested using website (found on Google Maps). I think that is a great idea and we should use that in place of the picture.

**Comment by robertbernardbrown** [comment]
Google open search in nearbySearch query makes sure that a restaurant is open before showing to our app
