### ISSUE TITLE
Timer display

### ISSUE THREAD

**Issue by cslewislives** [emswann/still-open#82]
1. Get the current time.
2. Compare the current time to each closing time of the restaurant.
3. If closing time is within 2 hours time frame, add time until closing to restaurant list. Estimate time to 15 minute intervals (round down vs rounding up - floor vs. ceiling).

**Comment by robertbernardbrown** [comment]
Changed name of issue to Timer Display - need to figure out how to display when restaurants close to people and how long they have until restaurants close.

In regards to the previous goal of this issue, we are already capturing open restaurants using open_now queries in the nearbySearch
